services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: ${dbName}
      POSTGRES_USER: ${dbUser}
      POSTGRES_PASSWORD: ${dbPassword}
    ports:
      - ${dbPort}:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data