services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=my_store
      - POSTGRES_USER=edca
      - POSTGRES_PASSWORD=admin123
    ports:
      - 5555:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - my_network
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5050:80
    networks:
      - my_network

networks:
  my_network:
    driver: bridge